In [195]:
import numpy as np
from sklearn import preprocessing

In [204]:
boston = np.genfromtxt(r"C:\Users\nisha\Downloads\bp.csv", delimiter = ',')
scaler = preprocessing.StandardScaler()
boston

array([[-0.40784991, -0.48772236, -1.2660231 , ...,  0.41057102,
        -1.09799011, 37.9       ],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.29116915,
        -0.52047412, 21.4       ],
       [ 0.1251786 , -0.48772236,  1.01599907, ..., -3.79579542,
         0.89107588, 12.7       ],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.33206621,
        -0.33404299, 20.8       ],
       [-0.41061997, -0.48772236, -1.15221381, ...,  0.203235  ,
        -0.74475218, 22.6       ],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.38787479,
        -1.35871335, 50.        ]])

In [205]:
boston.shape

(379, 14)

In [207]:
X = boston[:, :13]
Y = boston[:, 13]
X = np.insert(X, 13, 1, axis = 1)
scaler.fit(X)
scaler.transform(X)
X.shape, Y.shape

((379, 14), (379,))

In [208]:
def step_generic_gd(X, Y, l_rate, Z):
    M = np.zeros(14)
    N = np.zeros(14)
    k = 0
    for i in range(379):
        temp = Y[i]
        for j in range(14):
            temp -= (X[i][j] * Z[j])
            M[j] += (-2 / 379) * temp * X[i][j]                
    N = Z - l_rate * M
    return N

In [209]:
def generic_gd(X, Y, num_iterations, l_rate):
    Z = np.zeros(14)
    for i in range(num_iterations):
        Z = step_generic_gd(X, Y, l_rate, Z)
        #print(Z)
        #print(i, "Cost", cost(X, Y, Z))
    return Z        

In [210]:
def cost(X, Y, M):
    total_cost = 0
    temp = 0
    for i in range(379):
        temp = 0
        for j in range(14):
            temp += X[i][j] * M[j]
        total_cost += (1 / 379) * (Y[i] - temp)**2
    return total_cost        

In [225]:
M = np.zeros(14)
def run():
    num_iterations = 1000
    l_rate = 0.5    
    M = generic_gd(X, Y, num_iterations, l_rate)
    return M

In [226]:
run()

array([-2.85435639,  2.41324302, -1.26022825,  2.21820626, -0.10412487,
        5.06897619,  1.77965199, -0.93341882,  0.68361878, -0.37525592,
       -0.69319389,  0.61102157, -1.42194956, 22.44716749])

In [227]:
test = np.genfromtxt(r"C:\Users\nisha\Downloads\test.csv", delimiter = ',')
test = np.insert(test, 13, 1, axis = 1)
scaler.transform(test)
test.shape

(127, 14)

In [228]:
M = run()
Y1 = np.zeros(127)
for i in range(127):
    for j in range(14):
        Y1[i] += test[i][j] * M[j]
Y1

array([ 3.37285835, 23.07770084, 21.4724155 , 20.31191539, 20.32656663,
        7.72617042, 30.12006508, 23.06753199, 17.69294504, 18.65668985,
       20.58444622, 20.02300791, 18.21225362, 19.62173975, 48.85319389,
       21.61021059, 17.79851812, 25.36406403, 18.87675388, 31.44511704,
       22.21247308, 19.93765402, 29.79523533, 38.99722113, 33.43570761,
       12.86670335, 20.1544118 , 29.61633019, 29.46762032, 39.18424699,
       19.43632403, 18.39530876, 24.16618705, 24.75085406, 14.19281786,
       27.08119792, 23.94301415, 21.90854047, 23.57270336, 12.92129693,
       -0.78886555, 25.68468049, 28.97745656, 22.51002821, 17.66428999,
       -1.64627959, 43.78491825, 26.03160057, 37.02568006, 19.46610189,
       15.22456664, 45.05054832, 20.31042839, 17.49293118, 19.41873595,
       19.23312377, 17.90672979, 18.4919584 , 15.83481635, 18.38381698,
        6.2184382 , 27.25701213, 23.10094098, 22.33883594, 16.00146048,
       10.65837376, 35.76746039, 19.81098531, 27.39477835, 19.01

In [229]:
np.savetxt("gd_boston4.csv", Y1, delimiter=",", fmt='%1.9f')