In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [4]:
# no hidden layer weights
weights = 2* np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[ 0.80323912],
        [-0.51141776]]), array([0.64833656]))

In [5]:
# forward propagation without any hidden layer
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[0.65663551],
       [0.53417632],
       [0.81024081],
       [0.71913155]])

In [6]:
# one hidden layer weights
wh = 2* np.random.random((2, 2)) - 1
bh = 2* np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1,1)) - 1
                        

In [9]:
#here farguments  for the the above random functions are of the following formats
#random(no of units in input layer,no of units in hidden layer)
#multplying by 2 and then subtracting 1 gets the range to be from -1 to 1
#in bh 1 bias goes to 2 units of hidden layer thus  (1,2) in that case

In [8]:
# forward propagation with one hidden layer
output0 = X
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden, wo) + bo)
output

array([[0.58694226],
       [0.5800451 ],
       [0.56539251],
       [0.56369032]])