In [3]:
import tensorflow as tf

In [6]:
#constants
a = tf.constant(2)
b = tf.constant(3)
c = a + b
sess = tf.Session()
sess.run(a)

a1 = tf.constant([[3,3]])
a2 = tf.constant([[3],[3]])
res = tf.matmul(a1, a2)
sess.run(res)

array([[18]])

In [31]:
#session
a = tf.constant(2)
b = tf.constant(3)
c = tf.add(a, b)
#print(c.eval())
with tf.Session() as abc:
   print(c.eval())

5


In [45]:
#variables
var1 = tf.Variable(100)
var2 = tf.Variable(3)
sum = tf.add(var1, var2)
sess= tf.Session()
#sess1= tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(sum))

assign = var1.assign(1232)
sess.run(assign)
sess.run(var1)
sess.run(sum)

103


1235

In [56]:
x = tf.placeholder(tf.int32, shape = (2,3))
y = x * tf.constant(12)
sess.run(y, feed_dict={x:[[1,2,3], [4,5,6]]})

array([[12, 24, 36],
       [48, 60, 72]], dtype=int32)

In [1]:
#placeholder is a way to tell tensorflow code and pass on the values afterwords when we run that code

In [11]:
x = tf.placeholder(tf.int16)
y = tf.constant(12)
sess.run(y)
#here we'll get an error saying that we must feed value to x
#You must feed a value for placeholder tensor is the error that we get
#as the above code is independent of x thus it runs fine

12

In [15]:
x = tf.placeholder(tf.int16)
y = x * tf.constant(12)
sess.run(y)
#now as the value of y depends on the value of x thus we can see that we get an error
#as we have x which is a placeholder which we need to pass
#so how to pass value in a placeholder????

TypeError: Input 'y' of 'Mul' Op has type int32 that does not match type int16 of argument 'x'.

In [18]:
#to do so we need to pass an argument called feed_dictionary 
x = tf.placeholder(tf.int32)
y = x * tf.constant(12)
sess.run(y,feed_dict = {x:10})
#here in can imagine like we want to multipply diff numbers to only 12 
#so every time we can pass diff placeholder values which can do the same

120

In [20]:
x = tf.placeholder(tf.int32)
y = x * tf.constant(12)
sess.run(y,feed_dict = {x:[1,2]})
#here there is no shape which has been passed

array([12, 24])

In [23]:
x = tf.placeholder(tf.int32,shape=(2,3))
#thiss shape means 2 rows and 3 columns
y = x * tf.constant(12)
sess.run(y,feed_dict = {x:[1,2]})
#here the error corresponds tothe fact that we havent passed the correct values in placeholder but have specified its shappe

ValueError: Cannot feed value of shape (2,) for Tensor 'Placeholder_18:0', which has shape '(2, 3)'

In [26]:
x = tf.placeholder(tf.int32,shape=(2,3))
#thiss shape means 2 rows and 3 columns
y = x * tf.constant(12)
sess.run(y,feed_dict = {x:[[1,2,3],[4,5,6]]})
#so if we want any restriction on shape then we can pass it while writing our code

array([[12, 24, 36],
       [48, 60, 72]])

In [27]:
x = tf.placeholder(tf.int32)
y =tf.placeholder(tf.int32)
z = tf.constant(20)
sess.run(z)

20

In [29]:
x = tf.placeholder(tf.int32)
y =tf.placeholder(tf.int32)
v = 3 * x
sess = tf.Session()
sess.run(v)
#Explanation: Error because feed_dict value for x is not provided.

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_25' with dtype int32
	 [[node Placeholder_25 (defined at <ipython-input-29-7aa33aff8415>:1)  = Placeholder[dtype=DT_INT32, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder_25', defined at:
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\asyncio\base_events.py", line 427, in run_forever
    self._run_once()
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\asyncio\base_events.py", line 1440, in _run_once
    handle._run()
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tornado\gen.py", line 1233, in inner
    self.run()
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\IPython\core\interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\IPython\core\interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\IPython\core\interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\IPython\core\interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-7aa33aff8415>", line 1, in <module>
    x = tf.placeholder(tf.int32)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1747, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 6251, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "C:\Users\hp\Anaconda3\envs\tfp3.6\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_25' with dtype int32
	 [[node Placeholder_25 (defined at <ipython-input-29-7aa33aff8415>:1)  = Placeholder[dtype=DT_INT32, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [31]:
x = tf.placeholder(tf.int32)
y =tf.placeholder(tf.int32)
v = 3 * x
sess = tf.Session()
sess.run(v, feed_dict={x:10})
#Explanation : Since feed_dict is passed for x no error here.


30

In [33]:
x = tf.placeholder(tf.int32, shape = (2,3))
y = x * tf.constant(12)
sess.run(y, feed_dict={x:[[1,2], [4,5]]})
#Explanation: Shape of array passed in feed_dict doesn’t match. 
#You cannot feed value of shape (2, 2) for placeholder which has shape (2, 3)


ValueError: Cannot feed value of shape (2, 2) for Tensor 'Placeholder_32:0', which has shape '(2, 3)'