In [49]:
from sklearn import datasets
import numpy as np
import pandas as pd

In [51]:
diabetes = np.loadtxt("0000000000002329_training_diabetes_x_y_train.csv",delimiter=",")

In [53]:
diabetes
print(type(diabetes))

<class 'numpy.ndarray'>


In [64]:
Y_train = diabetes[:,10]

In [65]:
X_train = diabetes[:,0:10]

In [68]:
X_train
X_train.shape

(331, 10)

In [71]:
Y_train
Y_train.shape

(331,)

In [45]:
diabetes.describe()

# age         sex         bmi          bp          s1          s2  \
count  331.000000  331.000000  331.000000  331.000000  331.000000  331.000000   
mean    -0.000214   -0.000293    0.000053   -0.001045   -0.001423   -0.001220   
std      0.047207    0.047618    0.048627    0.047621    0.047371    0.046936   
min     -0.107226   -0.044642   -0.090275   -0.102071   -0.126781   -0.115613   
25%     -0.034575   -0.044642   -0.035307   -0.036656   -0.035968   -0.029967   
50%      0.005383   -0.044642   -0.008362   -0.005671   -0.004321   -0.004445   
75%      0.038076    0.050680    0.030979    0.032775    0.027326    0.028905   
max      0.110727    0.050680    0.170555    0.132044    0.153914    0.198788   

               s3          s4          s5          s6           Y  
count  331.000000  331.000000  331.000000  331.000000  331.000000  
mean     0.000440   -0.001473   -0.001594    0.000099  149.722054  
std      0.047303    0.046591    0.048088    0.047263   76.796907  
min     -0.102307   -0.076395   -0.126097   -0.137767   25.000000  
25%     -0.032356   -0.039493   -0.035817   -0.034215   84.000000  
50%     -0.006584   -0.002592   -0.005145   -0.001078  138.000000  
75%      0.026550    0.034309    0.032124    0.027917  202.000000  
max      0.181179    0.185234    0.133599    0.135612  346.000000

In [62]:
from sklearn import model_selection

In [66]:
print(X_train.shape)
print(Y_train.shape)

(331, 10)
(331,)


In [77]:
Y_train = Y_train.reshape(331,1)
Y_train.shape

(331, 1)

In [78]:
from sklearn.linear_model import LinearRegression

In [79]:
alg1 = LinearRegression()

In [80]:
alg1.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [83]:
coefficients = alg1.coef_
coefficients

array([[  21.73408096, -256.66866675,  569.60940087,  303.63233545,
        -833.11088526,  525.74313633,  136.07129167,  140.89458927,
         731.44498492,   53.32119133]])

In [87]:
X_test = np.loadtxt("0000000000002329_test_diabetes_x_test.csv",delimiter=",")

In [88]:
X_test

array([[ 0.02354575,  0.05068012, -0.0374625 , ..., -0.03949338,
        -0.03075121, -0.01350402],
       [-0.07816532, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.01811827, -0.08391984],
       [-0.03094232,  0.05068012,  0.00133873, ...,  0.1081111 ,
         0.08379677,  0.00306441],
       ...,
       [ 0.0090156 , -0.04464164, -0.01267283, ...,  0.03430886,
         0.02337484, -0.0052198 ],
       [ 0.01991321, -0.04464164, -0.03422907, ...,  0.03283281,
         0.02472532,  0.06933812],
       [ 0.01628068,  0.05068012,  0.00996123, ..., -0.03949338,
         0.01703713,  0.00720652]])

In [91]:
np.set_printoptions(precision=5)

In [92]:
Y_pred = alg1.predict(X_test)
Y_pred

array([[105.52975],
       [105.80392],
       [178.60857],
       [ 79.38288],
       [ 52.95869],
       [ 98.87264],
       [150.71755],
       [ 34.86515],
       [113.13536],
       [161.50184],
       [135.86156],
       [ 94.71592],
       [138.48094],
       [141.37442],
       [158.76863],
       [171.65289],
       [106.44836],
       [103.9266 ],
       [ 95.38694],
       [167.40118],
       [166.53426],
       [101.53465],
       [252.45036],
       [147.02259],
       [214.78907],
       [161.27557],
       [210.61315],
       [ 71.78092],
       [189.65032],
       [206.61343],
       [219.98643],
       [168.80193],
       [116.84846],
       [178.744  ],
       [ 77.03247],
       [ 59.54633],
       [111.56738],
       [156.95187],
       [154.59591],
       [198.94457],
       [115.53884],
       [153.46699],
       [ 84.9618 ],
       [113.70337],
       [142.14156],
       [147.3104 ],
       [ 82.78072],
       [ 77.89237],
       [128.99006],
       [261.58712],


In [93]:
pred1 = open('file','w')
np.savetxt("pred1.csv",Y_pred,delimiter=",")